import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { useTRPC } from "@/lib/trpc";
import { useEffectiveIdentity } from "@/hooks/useEffectiveIdentity";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";
import { Download, FileText, Loader2, ShieldCheck } from "lucide-react";
import { format } from "date-fns";

interface ComplianceReportCardProps {
  siteId?: string;
  unitId?: string;
  startDate: Date | undefined;
  endDate: Date | undefined;
  siteName?: string;
  unitName?: string;
}

export function ComplianceReportCard({
  siteId,
  unitId,
  startDate,
  endDate,
  siteName,
  unitName,
}: ComplianceReportCardProps) {
  const { effectiveOrgId } = useEffectiveIdentity();
  const trpc = useTRPC();
  const [exportFormat, setExportFormat] = useState<"csv" | "pdf">("csv");

  // tRPC mutation for exporting compliance reports
  const exportMutation = useMutation({
    ...trpc.reports.export.mutationOptions(),
    onSuccess: (data) => {
      // Download file
      const blob = new Blob([data.content], { type: data.contentType });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = data.filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      toast.success("Compliance report exported");
    },
    onError: (err) => {
      console.error("Export error:", err);
      toast.error("Failed to export report");
    },
  });

  const handleExport = (formatType: "csv" | "pdf") => {
    if (!startDate || !endDate) {
      toast.error("Please select a date range");
      return;
    }

    // Check authentication
    if (!effectiveOrgId) {
      toast.error("Session expired. Please sign in again.");
      window.location.href = "/auth";
      return;
    }

    setExportFormat(formatType);

    // Use tRPC mutation for export
    exportMutation.mutate({
      organizationId: effectiveOrgId,
      startDate: format(startDate, "yyyy-MM-dd"),
      endDate: format(endDate, "yyyy-MM-dd"),
      reportType: "compliance",
      format: formatType === "pdf" ? "html" : "csv",
      siteId: unitId ? undefined : siteId,
      unitId: unitId || undefined,
    });
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-safe/10 text-safe">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <CardTitle>Compliance Report</CardTitle>
              <CardDescription className="mt-1">
                Complete audit-ready report with all temperature logs, exceptions,
                corrective actions, and compliance status
              </CardDescription>
            </div>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between">
          <div className="text-sm text-muted-foreground space-y-1">
            <p>Includes:</p>
            <ul className="list-disc list-inside text-xs space-y-0.5">
              <li>Site and unit information</li>
              <li>Manual logging interval compliance</li>
              <li>All temperature logs (manual + automated)</li>
              <li>Out-of-range flags with timestamps</li>
              <li>Missed manual log entries</li>
              <li>Corrective action notes</li>
              <li>User attribution for each entry</li>
            </ul>
          </div>
          <div className="flex items-center gap-2">
            <Button
              onClick={() => handleExport("csv")}
              disabled={exportMutation.isPending || !startDate || !endDate}
              variant="outline"
            >
              {exportMutation.isPending && exportFormat === "csv" ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <FileText className="w-4 h-4 mr-2" />
              )}
              Export CSV
            </Button>
            <Button
              onClick={() => handleExport("pdf")}
              disabled={exportMutation.isPending || !startDate || !endDate}
            >
              {exportMutation.isPending && exportFormat === "pdf" ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <Download className="w-4 h-4 mr-2" />
              )}
              Export PDF
            </Button>
          </div>
        </div>
        <div className="mt-4 p-3 bg-muted/50 rounded-lg">
          <p className="text-xs text-muted-foreground">
            Footer: "Generated by FrostGuard on {format(new Date(), "MMM d, yyyy 'at' h:mm a")}"
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
